mem:
	g++ -std=c++11 -O3 -funroll-loops mem.cpp -o mem
bandwidth:
	g++ -std=c++11 -O0 -funroll-loops bandwidth.cpp -o bandwidth
pagefault:
	g++ -std=c++11 -O3 -funroll-loops pagefault.cpp -o pagefault  # sudo ./pagefault
clean:
	rm -rf *o mem
	rm -rf *o bandwidth
	rm -rf *o pagefault
